### ISSUE TITLE
Poor user experience on mobile devices

### ISSUE THREAD

**Issue by launchpad001** [RIPE-NCC/db-web-ui#90]
After a major styling update (possibly #43), the user experience on mobile devices has significantly deteriorated.

Specifically, there are many unexplained blank spaces and line breaks that make the interface difficult to use. It seems likely that excessive padding or layout issues might be the cause.

You can reproduce and observe the problem by opening the site in a mobile device simulator via developer tools, or by accessing it directly on a smartphone.

It would be great if this could be addressed in future updates to improve mobile usability.

**Comment by eshryane** [comment]
Hello @rdp-studio we deployed a fix for the mobile view today, to reduce the amount of whitespace and also format the HTML to fit within the smaller width of mobile devices.

Please try it out and let us know what you think.

**Comment by rdp-studio** [comment]
I noticed that mobile adaptation for some pages and scenes was still not perfect. However, it's a significant improvement over before.

I hope you could further optimize the mobile user experience. But this issue has now been resolved, and thank you!

**Comment by eshryane** [comment]
Thanks for your feedback @rdp-studio
